### ISSUE TITLE
Bump aioredis version to +2.x

### ISSUE THREAD

**Issue by phenobarbital** [aio-libs/aiohttp-session#605] opened 2021-07-31 22:17 UTC
Hi!

there is a plan to work in a version with aioredis 2.0 support?, I made some local changes in the redis_storage (mostly removing the "create_pool" and alternately using the aioredis.ConnectionPool) and the library work without issues.

there is such a plan or I can send a PR with my changes?

**Comment by Dreamsorcerer** [comment] 2021-08-01 10:34
Duplicate of #528 

Yes, PRs would be welcome.

**Closed by Dreamsorcerer** 2021-08-01 10:34 UTC
