### ISSUE TITLE
RedisStorage updates max_age on every session_save

### ISSUE THREAD

**Issue by sapph1re** [aio-libs/aiohttp-session#332] opened 2018-10-14 00:35 UTC
Every time a request arrives and a response is sent, `save_session()` is called. And every time it updates session's `max_age` both by:
 - Sending a `Set-Cookie` with the same session ID, but with a new `max_age` and `expires`.
 - Updating the max age of the session in Redis, i.e. `ttl` of the session is reset.

So effectively the session never expires unless idle. I would expect `max_age` to implement an absolute timeout for a session. Instead, it updates the timeout on every request, thus breaking the logic of an absolute timeout, and acting more like an idle timeout.

In my opinion, the correct behaviour would be:
 1. `save_session()` updates the data in Redis, but just does not send `Set-Cookie` if the cookie is already set (session id doesn't change anyways).
 2. `save_session()` does not reset the `ttl` of the session in Redis.

**Comment by panagiks** [comment] 2018-10-14 05:29
Hello @sapph1re and thank you for the report.

You are correct about ttl in Redis and it seems to relate with [how Redis' SET command works](https://redis.io/commands/set):

> Any previous time to live associated with the key is discarded on successful SET operation.

The solution I see for this is delta-ing `max_age` with `session.created` to calculate `expire` [here](https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/redis_storage.py#L78) before saving to Redis (cc @asvetlov would you agree with this implementation ? If so I can prepare a patch + tests). I think data should be properly expired (regardless of my following statements).

After `v2.7.0` the case you describe should however return an emptied session to you (since on the Session constructor the explicit `created` time is checked against `max_age`). Can you confirm that this is the case ?

Regarding the cookie returned there are a couple issues.

- There are storages that keep the data in the cookie value (see `EncryptedCookieStorage` and `NaClCookieStorage`). They need the cookie to be updated in order to update the session's contents. Cookie is set in the middleware which is storage agnostic (and IMO should stay that way).
- It's a bit of a gray area RFC-wise. As [RFC 6265 Sec-5.3 states](https://tools.ietf.org/html/rfc6265.html#section-5.3):

> If the cookie store contains a cookie with the same name, domain, and path as the newly created cookie: .... 3.  Update the creation-time of the newly created cookie to match the creation-time of the old-cookie.

So technically when max_age is specified (and not relied on `Expires`) the user-agent should properly handle the cookie. The problem here is that a) Some browsers still rely solely on `Expires` (AFAIK) and b) I'm not entirely sure (i.e. have no data on) how many user-agents implement the above directive.

**Comment by asvetlov** [comment] 2018-10-14 13:46
Please correct me if I'm wrong but now the library uses TTL for controlling inactive session expiration. We have the consistent behavior for all supported storages, not only limiting to Redis.

This is a valuable behavior. For example, very many sites want to drop logged user after some (a relative short) inactivity period.

@sapph1re asks for another thing: a total expiration time. I can imagine how can it be useful too -- but it is a different functionality. If you want to implement it -- you are welcome (please care about backward compatibility though).

**Comment by asvetlov** [comment] 2018-10-14 13:51
Hmm, I've realized that last changes from @panagiks violate the expiration logic.
We need consistency between storage implementations first.

**Comment by panagiks** [comment] 2018-10-14 17:35
To be honest I was under the false impression that the expected behavior for expiry is a ttl from the initial creation time. If this is not the case, both of my last changes (adding ttl to `EncryptedCookieStorage` fernet and invalidating sessions with `now - created > max_age`) as well as my suggestion above contradict with the expected behavior you are describing.

My suggestion would be to open a new issue to properly document the expected behavior (I suggest an issue in order to have a discussion so we can preemptively cover edge cases, or at least try).

With this collection of rules I can then write a new set of tests that will guarantee the business logic of the library (preferably in a storage agnostic way). 

Finally I think that since the suggestion has moved from in-project storages to third-party storage implementation, it would be best to crate a) a basic checklist of expected storage behavior and b) a baseline testing guide for storages.

Finally if you have any specific change in mind to fix the logic-breaking behavior I introduced please let me know and I will look into it as soon as possible :)

**Comment by sapph1re** [comment] 2018-10-15 00:33
Oh, I didn't realize the library is designed to use max_age as an idle timeout.
I'm following the owasp's guide on security, which recommends to implement both idle and absolute timeouts, as well as a renewal timeout.
I will use the library differently then, thanks. Will implement absolute timeout and renewal timeout in the app, and rely on the library about the idle timeout.
Thank you, guys.

**Comment by Dreamsorcerer** [comment] 2022-01-29 15:12
I think we can close this as expected behaviour then. If you consider the most common cases for websites, it's not expected for the user to suddenly be logged out while actively using the website.

We can look at the possibility of an absolute timeout in a PR, but I'm not sure it's a high priority.

**Closed by Dreamsorcerer** 2022-01-29 15:12 UTC
